### ISSUE TITLE
B+树代码交流

### ISSUE THREAD

**Issue by richardlzx** [zhiyiYo/cmu15445-fall2020#1]
大佬我最近也在做CMU15445 2020的实验，最近在做第二个project参照的您的代码，出了一点问题，想和您交流一下，不知是否方便呢？我的vx：zxl_Nefelibata

**Comment by zhiyiYo** [comment]
有问题可以看下我的博客

**Comment by zhiyiYo** [comment]
或者直接在这边交流

**Comment by richardlzx** [comment]
好的好的，就是目前我在做B+树这个实验，是在buffer pool这个实验已经通过的情况下做的。但是在B+树中新建节点时要调用NewPage这个函数来向buffer pool申请页面，如果没有则抛出out memory异常。整个B+树实验我是在理解的基础上参考大佬的代码敲得，但却没有通过，因为有些地方写法和您不太一样，我怀疑是自己写的问题，所以把所有B+树实验涉及的代码都直接copy您的github上的代码，还是报同样的错误，排查了很久都没找到bug，所以来请教一下大佬。

![C(CYA4J}L}4V26GF}VO@NXN](https://github.com/zhiyiYo/cmu15445-fall2020/assets/74773248/05c4d50e-b5fc-47b7-89a2-df6e5a128ce2)

**Comment by zhiyiYo** [comment]
buffer pool 实验有测试过 grade scope 上的测试用例吗

**Comment by zhiyiYo** [comment]
正常情况下应该不会抛 oom 异常的

**Comment by richardlzx** [comment]
我做的也是2020年的，因为目前grade scope已经关了。我用的代码是一个博主提供的，他的gitee（https://gitee.com/kangyupl/bustub）提供了干净的2020bustub代码，并且提供了他扒下来的完整测试代码，我在上面做的并且已经通过了buffer pool的全部测试，如下，所以我也感觉很迷哈哈哈。
![ZY3PD SVWR5S@ ZS)JIP5O](https://github.com/zhiyiYo/cmu15445-fall2020/assets/74773248/e814b3d7-44ef-44c4-a7bf-95821b8c21c9)

**Comment by richardlzx** [comment]
我做的也是2020年的，因为目前grade scope已经关了。我用的代码是一个博主提供的，他的gitee（https://gitee.com/kangyupl/bustub）提供了干净的2020bustub代码，并且提供了他扒下来的完整测试代码，我在上面做的并且已经通过了buffer pool的所有测试，如下，buffer pool没问题的话全部用的您B+树代码还能出问题我也很迷（😂）。
![ZY3PD SVWR5S@ ZS)JIP5O](https://github.com/zhiyiYo/cmu15445-fall2020/assets/74773248/33d1256c-0299-446a-a793-c2d6b76b352f)

**Comment by zhiyiYo** [comment]
实在不行的话就把 buffer pool 替换成我的吧

**Comment by richardlzx** [comment]
好滴好滴，我试一下！！

**Comment by richardlzx** [comment]
还真是buffer pool的问题人麻了，通过所有测试啦谢谢大佬!!
